export const colors = {
  primary: {
    DEFAULT: "#e5000f",
    hover: "#c9000d",
    active: "#a8000b",
    darkText: "#ff5a64",
    dark: "#ff3344",
    darkHover: "#ff4d5a",
    darkActive: "#e6192b",
    darkAccent: "#ff6b76",
  },
  accent: {
    yellow: "#cc9900",
    yellowLight: "#fffdf0",
    yellowDark: "#2a2a1a",
    orange: "#ff8c00",
    blue: "#2222ff",
    blueDark: "#6ba3ff",
  },
  light: {
    bgPrimary: "#faf9f5",
    bgSecondary: "#ffffff",
    bgTertiary: "#f2efe6",
    textPrimary: "#2d2c33",
    textSecondary: "#121116",
    textMuted: "#6e6b75",
    borderColor: "#e5e0d3",
    borderLight: "#eee9dd",
    boxShadow: "rgba(25, 20, 15, 0.05)",
    clickableActive: "#eae4d6",
    gridColor: "rgba(60, 50, 40, 0.045)",
  },
  dark: {
    bgPrimary: "#121215",
    bgSecondary: "#1a1a20",
    bgTertiary: "#22222a",
    textPrimary: "#dcdce5",
    textSecondary: "#fafafc",
    textMuted: "#9d9eae",
    borderColor: "#2c2c38",
    borderLight: "#23232f",
    boxShadow: "rgba(0, 0, 0, 0.5)",
    clickableActive: "#2c2c3a",
    gridColor: "rgba(255, 255, 255, 0.04)",
    primary: "#ff3344",
    primaryHover: "#ff4d5a",
    primaryActive: "#e6192b",
    primaryAccent: "#ff6b76",
  },
};

export const typography = {
  fontSans: '"Assistant", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontSerif: '"Lora", Georgia, Cambria, "Times New Roman", Times, serif',
  fontMono: '"IBM Plex Mono", "Geist Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
};
